--- #YAML:1.0
name:                Every
version:             0.01
abstract:            return true every N cycles or S seconds
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ted Zlatanov <tzz@lifelogs.com>
